### ISSUE TITLE
USCore 5.0.1 SDOH Observation tests use the wrong category

### ISSUE THREAD

**Issue by karlnaden** [inferno-framework/us-core-test-kit#78]
SDOH Observation search tests use category = survey instead of sdoh. 

I suspect the generator isn't correctly handling the fact that the [SDOH Observation](http://hl7.org/fhir/us/core/STU5/StructureDefinition-us-core-observation-sdoh-assessment.html) profile is based on the [Survey Observation](http://hl7.org/fhir/us/core/STU5/StructureDefinition-us-core-observation-survey.html) profile.

**Comment by yunwwang** [comment]
The reason is the category=sdoh is optional for SDOH Observation so we cannot use that to find SDOH observations

**Comment by karlnaden** [comment]
Interesting, I had not noticed that and wonder why the decision was made to make it optional.

The specific thing that triggered this ticket was running the US Core 5.0.1 SDOH Observation tests against the inferno reference server and getting a whole lot of conformance validation failures due to smoking status resources:
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/86612928/194077248-71030bea-eae4-4a9e-b25a-a78ca96f7d42.png">

Maybe this is just poor data on that test server, but if things that are not SDOH observations are going to be returned from the query, the seems like there needs to be another step before the conformance validation check to filter down to just the ones that will be expected to pass the check.  The category seemed like a nice way to do that, but if it can't be relied upon, then what can? If there isn't anything, then seems like worthwhile feedback to the US Core team.

**Comment by yunwwang** [comment]
Yes. That is correct. First the Inferno Demo server has data conforming to US Core v3.1.1. We have a PR to upgrade the data to US Core v4.0.0. US Core v5.0.1 will be the next target.
There are two profiles in US Core v5.0.1 having `category = survey`. One is Observation Survey. The other is SDOH Assessment. As mentioned above, there are not many difference between these two. One difference is that SDOH has an optional slice of `category=sdoh`. This is optional so server is not required to populate value. The other difference is the SDOH has a preferred binding on Observation.code to US Core Common SDOH Assessment value set. The binding is preferred which server may or may not observe. 
That means when receiving an Observation with `category=survey`, there is no reliable way to say if the resource is Observation Survey or SDOH Assessment. 
Since SDOH Assessment "inherits" from Observation Survey, we treat Observation Survey as a "abstract" parent profile. The same way we treat US Core Vital Sign profile. It works at least in US Core v5.0.1
If there are new profiles added in the future US Core release, then we will ask the IG to provide more specific logic to distinguish all the resources having `category=survey`.

**Comment by karlnaden** [comment]
Got it - so the assumption is that `category = survey` means SDOH since no other non-abstract profiles under it.  Thanks

**Comment by karlnaden** [comment]
Got it - so 'category = comment' means it must be SDOH because there's no other non-abstract options. Makes sense for now.
